train_batch_size: 512
epochs: 1

# neg_sampling: 
#   popularity: 1

eval_args: 
  split: {'RS':[1.0,0.0,0.0]}
  group_by: user
  order: TO
  # mode: pop0

data_path: 'dataset/dkt'
use_gpu: True
gpu_id: 0
device: 'cuda'


# data preprocessing
USER_ID_FIELD: userID
ITEM_ID_FIELD: assessmentItemID
RATING_FIELD: answerCode
TIME_FIELD: Timestamp

load_col:
    inter: [userID, assessmentItemID, answerCode, Timestamp]
    user: [userID]
    item: [assessmentItemID, testId, KnowledgeTag]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
val_interval:
    answerCode: "[0,1]"
    Timestamp: "[97830000, inf)"